// @ts-expect-error Generated by OpenNext before Wrangler builds this entrypoint.
import nextWorker from './.open-next/worker.js'

const SCHEDULED_PUBLISH_PATH = '/api/internal/scheduler/publish'

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    return nextWorker.fetch(request, env, ctx)
  },

  async scheduled(controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    if (controller.cron !== '*/1 * * * *') {
      throw new Error(`Unexpected cron trigger: ${controller.cron}`)
    }

    const request = new Request(`https://internal${SCHEDULED_PUBLISH_PATH}`, {
      method: 'POST',
      headers: {
        authorization: `Bearer ${env.CRON_INTERNAL_TOKEN}`,
        'content-type': 'application/json',
        'x-cron-scheduled-time': String(controller.scheduledTime),
      },
    })

    const response = await nextWorker.fetch(request, env, ctx)
    if (!response.ok) {
      const body = await response.text()
      throw new Error(`Scheduled publish failed: ${response.status} ${body}`)
    }
  },
} satisfies ExportedHandler<CloudflareEnv>
