import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const read = (relativePath: string) => readFileSync(resolve(process.cwd(), relativePath), 'utf8')

describe('Creator Center admin extension', () => {
  it('keeps Payload /admin bound to the native Users admin gate', () => {
    const config = read('src/payload.config.ts')
    const users = read('src/collections/Users.ts')

    expect(config).toContain('user: Users.slug')
    expect(config).not.toContain('CreatorCenterAction')
    expect(config).not.toContain('creatorCenter:')
    expect(users).toContain("import { payloadAdminOnly } from '@/auth/payload-admin-access'")
    expect(users).toContain('admin: payloadAdminOnly')
  })

  it('makes the content version explicit inside the publish preview', () => {
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')
    expect(publisher).toContain('<strong>发布预览</strong>')
    expect(publisher).toContain("aria-label={'预览版本 ' + draft.version}")
    expect(publisher).toContain('版本 v{draft.version}')
    expect(publisher).toContain('当前草稿版本')
  })

  it('uses the canonical structured article renderer in publish preview', () => {
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')
    expect(publisher).toContain("import ArticleStructuredRenderer from '../../../components/ArticleStructuredRenderer.js'")
    expect(publisher).toContain('<ArticleStructuredRenderer document={articleDocument} />')
    expect(publisher).not.toContain('{articleDocument.blocks.map((block) => {')
  })

  it('preserves the full publish return path when authentication expires', () => {
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')
    expect(publisher).toContain('const returnTo = window.location.pathname + window.location.search + window.location.hash')
    expect(publisher).toContain("router.replace(\`/login?returnTo=\${encodeURIComponent(returnTo)}\`)")
    expect(publisher).toContain("const loginPath = window.location.pathname.startsWith('/admin/') ? '/admin/login' : '/login'")
    expect(publisher).toContain("router.replace(loginPath + '?returnTo=' + encodeURIComponent(returnTo))")
  })

  it('shares published creator content through the canonical public slug URL', () => {
    const contentList = read('src/app/(payload)/v1beta/CreatorContentList.tsx')
    expect(contentList).toContain("const sharePath = '/content/' + encodeURIComponent(item.slug || item.id)")
    expect(contentList).toContain("const shareUrl = window.location.origin + sharePath")
    expect(contentList).toContain("typeof navigator.share === 'function'")
    expect(contentList).toContain("await navigator.share({ title: item.title, url: shareUrl })")
    expect(contentList).toContain('sharePublishedContent(item)')
    expect(contentList).toContain('await navigator.clipboard.writeText(shareUrl)')
    expect(contentList).toContain('公开链接已复制。')
  })

  it('redirects creator content management auth expiry to admin login', () => {
    const contentList = read('src/app/(payload)/v1beta/CreatorContentList.tsx')
    expect(contentList).toContain("const returnTo = window.location.pathname + window.location.search + window.location.hash")
    expect(contentList).toContain("window.location.assign(loginPath + '?returnTo=' + encodeURIComponent(returnTo))")
    expect(contentList).toContain("if (response.status === 401)")
  })

  it('keeps creator content loader identity aligned with its auth redirect dependency', () => {
    const list = read('src/app/(payload)/v1beta/CreatorContentList.tsx')
    expect(list).toContain('const load = useCallback(async (cursor: string | null = null) => {')
    expect(list).toContain('}, [loginPath, status, type])')
  })

  it('only advances the saved article snapshot after the content write succeeds', () => {
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')
    expect(publisher).toContain('let nextSavedArticleSerialized: string | null = null')
    expect(publisher).toContain('nextSavedArticleSerialized = serialized')
    expect(publisher).not.toContain('bodyRef = (await uploadFile(bodyFile)).url\n        setSavedArticleSerialized(serialized)')
    expect(publisher).toContain('if (nextSavedArticleSerialized !== null) setSavedArticleSerialized(nextSavedArticleSerialized)')
  })

  it('cancels stale creator content list requests', () => {
    const list = read('src/app/(payload)/v1beta/CreatorContentList.tsx')
    expect(list).toContain('const activeRequestRef = useRef<AbortController | null>(null)')
    expect(list).toContain('activeRequestRef.current?.abort()')
    expect(list).toContain('const controller = new AbortController()')
    expect(list).toContain('signal: controller.signal')
    expect(list).toContain("cause.name === 'AbortError'")
    expect(list).toContain('if (requestId !== requestIdRef.current) return')
  })

  it('cancels stale creator content list requests during refresh and navigation', () => {
    const contentList = read('src/app/(payload)/v1beta/CreatorContentList.tsx')
    expect(contentList).toContain('const activeRequestRef = useRef<AbortController | null>(null)')
    expect(contentList).toContain('activeRequestRef.current?.abort()')
    expect(contentList).toContain('signal: controller.signal')
    expect(contentList).toContain('requestIdRef.current += 1')
    expect(contentList).toContain('controller.signal.aborted')
  })

  it('redirects creator audience auth expiry to admin login', () => {
    const audience = read('src/app/(payload)/v1beta/CreatorAudienceSummary.tsx')

    expect(audience).toContain("const returnTo = window.location.pathname + window.location.search + window.location.hash")
    expect(audience).toContain("window.location.assign(loginPath + '?returnTo=' + encodeURIComponent(returnTo))")
    expect(audience.match(/response\.status === 401/g)?.length).toBe(2)
  })

  it('uses the W02-backed Payload admin request principal without a second login/session system', () => {
    const view = read('src/app/(payload)/v1beta/CreatorCenter.tsx')

    expect(view).toContain('AdminViewServerProps')
    expect(view).toContain('initPageResult.req.user')
    expect(view).not.toContain('sessionStorage')
    expect(view).not.toContain('accessToken')
    expect(view).not.toContain('refreshToken')
  })

  it('redirects moderation auth expiry to admin login', () => {
    const moderation = read('src/app/(payload)/v1beta/CreatorModerationQueue.tsx')
    expect(moderation).toContain("const returnTo = window.location.pathname + window.location.search + window.location.hash")
    expect(moderation).toContain("window.location.assign('/admin/login?returnTo=' + encodeURIComponent(returnTo))")
    expect(moderation).toContain('if (response.status === 401)')
  })

  it('hardens short-video media validation and cover selection', () => {
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')

    expect(publisher).toContain('const isVideoAsset')
    expect(publisher).toContain('短视频至少需要添加一个视频素材。')
    expect(publisher).toContain('const resolveCoverRef')
    expect(publisher).toContain('assets.find(isImageAsset)?.url ?? null')
    expect(publisher).toContain("'当前封面'")
    expect(publisher).toContain('默认使用第一张图片素材')
    expect(publisher).toContain('resolveCoverRef(type, assets, coverRef)')
  })

  it('paginates organization members from the canonical cursor response', () => {
    const members = read('src/app/(payload)/v1beta/CreatorContentOrganizationMembers.tsx')
    expect(members).toContain('const [memberCursor, setMemberCursor] = useState<string | null>(null)')
    expect(members).toContain('const [memberHasMore, setMemberHasMore] = useState(false)')
    expect(members).toContain("const params = new URLSearchParams({ limit: '50' })")
    expect(members).toContain("if (cursor) params.set('cursor', cursor)")
    expect(members).toContain('async function loadMoreMembers()')
    expect(members).toContain('加载更多成员')
    expect(members).toContain('page.nextCursor')
    expect(members).toContain('page.hasMore')
  })

  it('registers Word import through the structured editor plugin registry', () => {
    const registry = read('src/components/article-editor-plugins.ts')
    const plugin = read('src/components/article-editor-word-import-plugin.tsx')
    const editor = read('src/components/ArticleStructuredEditor.tsx')
    expect(registry).toContain("import { articleWordImportPlugin } from './article-editor-word-import-plugin.js'")
    expect(registry).toContain('export const articleEditorPlugins: readonly ArticleEditorPlugin[] = [articleWordImportPlugin]')
    expect(plugin).toContain("id: 'word-import'")
    expect(plugin).toContain('Toolbar: WordImportToolbar')
    expect(plugin).toContain('onImport={updateDocument}')
    expect(editor).not.toContain("import ArticleWordImportButton from './ArticleWordImportButton.js'")
    expect(editor).not.toContain('<ArticleWordImportButton disabled={disabled} onImport={emit} />')
  })

  it('makes Word import available in the Creator Studio structured article editor', () => {
    const editor = read('src/components/ArticleStructuredEditor.tsx')
    const plugin = read('src/components/article-editor-word-import-plugin.tsx')
    const importer = read('src/components/ArticleWordImportButton.tsx')
    const adapter = read('src/features/word-import/article-document-adapter.ts')
    expect(plugin).toContain("import ArticleWordImportButton from './ArticleWordImportButton.js'")
    expect(plugin).toContain('<ArticleWordImportButton disabled={disabled} onImport={updateDocument} />')
    expect(importer).toContain('accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document"')
    expect(importer).toContain("fetch('/api/v1/media'")
    expect(importer).toContain("new Blob([bytes as BlobPart], { type: mimeType })")
    expect(importer).toContain('collectImportedImages(imported.blocks)')
    expect(adapter).toContain('for (const url of Array.from(new Set(rowImages)))')
    expect(importer).toContain('articleDocumentFromImportedDocument')
    expect(adapter).toContain("createArticleMediaBlock('image'")
    expect(adapter).toContain('Word 表格已转为段落文本')
    expect(adapter).toContain('for (const url of Array.from(new Set(rowImages)))')
  })

  it('exposes the editor plugin host and publish-time registry', () => {
    const editor = read('src/components/ArticleStructuredEditor.tsx')
    const plugin = read('src/components/ArticleEditorPlugin.ts')
    const registry = read('src/components/article-editor-plugins.ts')
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')
    expect(plugin).toContain('export type ArticleEditorPluginContext')
    expect(plugin).toContain('Toolbar?: ComponentType<ArticleEditorPluginContext>')
    expect(plugin).toContain('Panel?: ComponentType<ArticleEditorPluginContext>')
    expect(plugin).toContain('updateDocument: (next: ArticleDocument) => void')
    expect(plugin).toContain("insertMedia: (type: 'image' | 'gallery', assetUrls?: string[]) => void")
    expect(editor).toContain('plugins?: readonly ArticleEditorPlugin[]')
    expect(editor).toContain('const orderedPlugins = useMemo(')
    expect(editor).toContain('normalizeArticleEditorPlugins(plugins)')
    expect(editor).toContain("<Toolbar key={plugin.id + ':toolbar'}")
    expect(editor).toContain('<Panel key={plugin.id + \':panel\'}')
    expect(registry).toContain('export const articleEditorPlugins: readonly ArticleEditorPlugin[] = [articleWordImportPlugin]')
    expect(publisher).toContain('plugins={articleEditorPlugins}')
  })

  it('filters only already-loaded creator content without adding a search endpoint', () => {
    const list = read('src/app/(payload)/v1beta/CreatorContentList.tsx')
    expect(list).toContain('const [localFilter, setLocalFilter] = useState(\'\')')
    expect(list).toContain('const visibleItems = useMemo(() => {')
    expect(list).toContain('筛选已加载内容（标题或 ID）')
    expect(list).toContain('当前筛选只作用于已经加载的内容；可清空筛选或继续加载更多。')
    expect(list).toContain('{visibleItems.map((item) => (')
  })

  it('displays the canonical zero-based member position rather than a paginated row index', () => {
    const members = read('src/app/(payload)/v1beta/CreatorContentOrganizationMembers.tsx')
    expect(members).toContain('<span>位置 {member.position + 1}</span>')
    expect(members).not.toContain('<span>位置 {index + 1}</span>')
  })

  it('filters only already-loaded organization members and candidates', () => {
    const members = read('src/app/(payload)/v1beta/CreatorContentOrganizationMembers.tsx')
    expect(members).toContain("const [candidateFilter, setCandidateFilter] = useState('')")
    expect(members).toContain("const [memberFilter, setMemberFilter] = useState('')")
    expect(members).toContain('const filteredCandidates = useMemo(() => {')
    expect(members).toContain('const filteredMembers = useMemo(() => {')
    expect(members).toContain('筛选已加载内容（标题或 ID）')
    expect(members).toContain('筛选已加载成员（标题或 ID）')
    expect(members).toContain('members.findIndex((item) => item.relationshipId === member.relationshipId)')
  })

  it('exposes canonical public actions for organization members', () => {
    const members = read('src/app/(payload)/v1beta/CreatorContentOrganizationMembers.tsx')
    expect(members).toContain("member.contentSlug || member.contentId")
    expect(members).toContain("href={'/content/' + encodeURIComponent(member.contentSlug || member.contentId)}")
    expect(members).toContain('target="_blank"')
    expect(members).toContain('async function shareMemberContent(member: MemberItem)')
    expect(members).toContain("await navigator.share({ title: member.title, url: shareUrl })")
    expect(members).toContain('await navigator.clipboard.writeText(shareUrl)')
    expect(members).toContain('公开链接已复制。')
  })

  it('paginates published content candidates for organization membership', () => {
    const members = read('src/app/(payload)/v1beta/CreatorContentOrganizationMembers.tsx')
    expect(members).toContain("const [candidateCursor, setCandidateCursor] = useState<string | null>(null)")
    expect(members).toContain("const [candidateHasMore, setCandidateHasMore] = useState(false)")
    expect(members).toContain("params.set('cursor', cursor)")
    expect(members).toContain("setCandidateCursor(page.nextCursor)")
    expect(members).toContain("setCandidateHasMore(page.hasMore)")
    expect(members).toContain('加载更多已发布内容')
    expect(members).not.toContain('limit=1000')
  })

  it('supports setting a Series or Collection cover during creation', () => {
    const organization = read('src/app/(payload)/v1beta/CreatorContentOrganization.tsx')
    expect(organization).toContain("coverRef: form.coverRef.trim() ? form.coverRef.trim() : null")
    expect(organization).toContain("uploadOrganizationCover(event, 'create')")
    expect(organization).toContain("setForm((current) => ({ ...current, coverRef: '' }))")
    expect(organization).toContain('disabled={!form.title.trim() || saving || coverUploading}')
  })

  it('manages Creator Studio organization covers through the existing media upload and PATCH flow', () => {
    const organization = read('src/app/(payload)/v1beta/CreatorContentOrganization.tsx')
    expect(organization).toContain("method: 'POST'")
    expect(organization).toContain("formData.append('file', file)")
    expect(organization).toContain("'/api/v1/media'")
    expect(organization).toContain("'Idempotency-Key': 'content-organization-cover-upload:'")
    expect(organization).toContain('accept="image/*"')
    expect(organization).toContain("coverRef: editForm.coverRef.trim() ? editForm.coverRef.trim() : null")
    expect(organization).toContain('清除封面')
    expect(organization).toContain('组织封面必须是图片文件。')
  })

  it('updates Series and Collection metadata through the canonical PATCH API', () => {
    const organization = read('src/app/(payload)/v1beta/CreatorContentOrganization.tsx')
    expect(organization).toContain("method: 'PATCH'")
    expect(organization).toContain("'If-Match': item.etag")
    expect(organization).toContain("'Idempotency-Key': 'content-organization-update:'")
    expect(organization).toContain("coverRef: editForm.coverRef.trim() ? editForm.coverRef.trim() : null")
    expect(organization).toContain("maxLength={512}")
    expect(organization).toContain("maxLength={4096}")
    expect(organization).toContain("setEditingOrganizationId(null)")
  })

  it('paginates Creator Studio Series and Collection organization lists', () => {
    const organization = read('src/app/(payload)/v1beta/CreatorContentOrganization.tsx')
    expect(organization).toContain("const [loadingMore, setLoadingMore] = useState(false)")
    expect(organization).toContain("if (cursor) params.set('cursor', cursor)")
    expect(organization).toContain("async function loadMoreOrganizations()")
    expect(organization).toContain("readPage(kind, controller.signal, loginPath, page.nextCursor)")
    expect(organization).toContain('加载更多')
    expect(organization).toContain('items: [...current[kind].items, ...next.items]')
  })

  it('connects Creator Studio organizations to canonical member attach, reorder and remove APIs', () => {
    const organization = read('src/app/(payload)/v1beta/CreatorContentOrganization.tsx')
    const members = read('src/app/(payload)/v1beta/CreatorContentOrganizationMembers.tsx')

    expect(organization).toContain('CreatorContentOrganizationMembers')
    expect(organization).toContain('成员管理')
    expect(organization).toContain('handleOrganizationChanged')
    expect(members).toContain("const params = new URLSearchParams({ limit: '50', status: 'PUBLISHED' })")
    expect(members).toContain("fetch('/api/creator/contents?' + params.toString()")
    expect(members).toContain("method: 'POST'")
    expect(members).toContain("method: 'PATCH'")
    expect(members).toContain("method: 'DELETE'")
    expect(members).toContain("'If-Match': etag")
    expect(members).toContain('contentId: selectedContentId')
    expect(members).toContain('position')
    expect(members).not.toContain('content_relationships')
    expect(members).not.toContain('getPayload(')
  })

  it('exposes Series and Collection management through the Creator Studio content authority', () => {
    const center = read('src/app/(frontend)/creator-center/CreatorStudio.tsx')
    const organization = read('src/app/(payload)/v1beta/CreatorContentOrganization.tsx')

    expect(center).toContain('CreatorContentOrganization')
    expect(center).toContain('id="content-organization"')
    expect(organization).toContain('/api/v1/series')
    expect(organization).toContain('/api/v1/collections')
    expect(organization).toContain("method: 'POST'")
    expect(organization).toContain("method: 'DELETE'")
    expect(organization).toContain("'If-Match': item.etag")
    expect(organization).toContain("'Idempotency-Key': 'content-organization:")
    expect(organization).not.toContain('content_series')
    expect(organization).not.toContain('content_collections')
    expect(organization).not.toContain('getPayload(')
  })

  it('embeds the existing publisher with a scoped W03 content bridge', () => {
    const view = read('src/app/(frontend)/creator-center/CreatorStudio.tsx')
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')
    const contentDetail = read('src/app/(frontend)/content/[contentId]/ContentDetailClient.tsx')
    const contentDetailPage = read('src/app/(frontend)/content/[contentId]/page.tsx')
    const homeFeed = read('src/app/(frontend)/HomeContentFeed.tsx')
    const contentBrowse = read('src/app/(frontend)/content/page.tsx')
    const page = read('src/app/(frontend)/publish/page.tsx')
    const contentClient = read('src/content/w03-content-client.ts')
    const createRoute = read('src/app/(payload)/api/creator/contents/route.ts')
    const updateRoute = read('src/app/(payload)/api/creator/contents/[contentId]/route.ts')
    const stateRoute = read('src/app/(payload)/api/creator/contents/[contentId]/state/route.ts')
    const preflightRoute = read('src/app/(payload)/api/creator/contents/[contentId]/preflight/route.ts')

    expect(view).toContain('<PublishComposer contentBasePath="/api/creator/contents" />')
    expect(publisher).toContain("contentBasePath = '/api/v1/contents'")
    expect(publisher).toContain("credentials: 'include'")
    expect(publisher).not.toContain('sessionStorage')
    expect(publisher).not.toContain('luckread.accessToken')
    expect(publisher).not.toContain('luckread.refreshToken')
    expect(publisher).not.toContain("Authorization', 'Bearer '")
    expect(publisher).toContain('const [draft, setDraft]')
    expect(publisher).toContain('const [savedBody, setSavedBody]')
    expect(publisher).toContain('const isUpdate = Boolean(draft?.id && draft.etag)')
    expect(publisher).toContain("method: isUpdate ? 'PATCH' : 'POST'")
    expect(publisher).toContain("'If-Match': draft!.etag")
    expect(publisher).toContain('async function discardDraft()')
    expect(publisher).toContain("method: 'DELETE'")
    expect(publisher).toContain("'If-Match': draft.etag")
    expect(publisher).toContain('useEffect')
    expect(publisher).toContain("searchParams.get('draft')")
    expect(page).toContain("normalizeContentType")
    expect(page).toContain("<PublishComposer initialType={initialType} />")
    expect(publisher).toContain("method: 'GET'")
    expect(publisher).toContain('window.history.replaceState')
    expect(publisher).toContain('async function copyDraftLink()')
    expect(publisher).toContain('navigator.clipboard.writeText')
    expect(publisher).toContain("'复制恢复链接'")
    expect(publisher).toContain('const stateLabel = draft?.state')
    expect(publisher).toContain("const reviewLocked = draft?.state === 'PENDING_REVIEW'")
    expect(publisher).toContain("const returnTo = window.location.pathname + window.location.search + window.location.hash")
    expect(publisher).toContain("router.replace('/login?returnTo=' + encodeURIComponent(returnTo))")
    expect(contentDetailPage).toContain('generateMetadata')
    expect(contentDetailPage).toContain('alternates:')
    expect(contentDetailPage).toContain('permanentRedirect')
    expect(contentDetail).toContain("const [actionMessage, setActionMessage] = useState('')")
    expect(homeFeed).toContain('const cover = item.coverRef')
    expect(homeFeed).toContain('alt={item.title ? item.title + copy.content.cover : copy.content.cover}')
    expect(homeFeed).not.toContain('item.coverRef || item.mediaRefs?.[0]')
    expect(homeFeed).toContain('content-feed-card-skeleton')
    expect(homeFeed).toContain('const [retryKey, setRetryKey] = useState(0)')
    expect(homeFeed).toContain('setRetryKey((value) => value + 1)')
    expect(homeFeed).toContain('Array.from({ length: 3 }')
    expect(homeFeed).toContain("const [error, setError] = useState(false)")
    expect(homeFeed).toContain('copy.content.error')
    expect(contentBrowse).toContain('content-feed-card-skeleton')
    expect(contentBrowse).toContain('Array.from({ length: 6 }')
    expect(contentBrowse).toContain('aria-busy="true"')
    expect(contentBrowse).toContain('aria-busy={loadingMore}')
    expect(contentBrowse).toContain('const requestIdRef = useRef(0)')
    expect(contentBrowse).toContain('const requestId = ++requestIdRef.current')
    expect(contentBrowse).toContain('if (requestId !== requestIdRef.current) return')
    expect(contentBrowse).toContain('role="status"')
    expect(read('src/app/(frontend)/styles.css')).toContain('@media (prefers-reduced-motion: reduce)')
    expect(read('src/app/(frontend)/styles.css')).toContain('.content-feed-card-skeleton')
    expect(contentDetail).toContain('copy.detail.linkError')
    expect(contentDetail).toContain("Network error. Could not generate a share link.")
    expect(contentDetail).toContain('content-detail-action-status')
    expect(contentDetail).toContain('const [retryKey, setRetryKey] = useState(0)')
    expect(contentDetail).toContain('setRetryKey((value) => value + 1)')
    expect(contentDetail).toContain('content-detail-retry')
    expect(contentDetailPage).toContain("/content/' + encodeURIComponent(content.slug)")
    expect(contentDetail).toContain('<main aria-busy={loading} className="content-detail">')
    expect(contentDetail).toContain('{copy.detail.loading}')
    expect(contentDetail).toContain("aria-label={content.title + ' ' + copy.detail.video + ' ' + (index + 1)}")
    expect(contentDetail).toContain('const controller = new AbortController()')
    expect(contentDetail).toContain('signal: controller.signal')
    expect(contentDetail).toContain("cause.name === 'AbortError'")
    expect(contentDetail).toContain('controller.abort()')
    expect(contentDetail).toContain("alt={content.title + ' ' + copy.detail.cover}")
    expect(contentDetail).toContain("alt={content.title + ' ' + copy.detail.image + ' ' + (index + 1)}")
    expect(read('src/app/(frontend)/styles.css')).toContain('.content-detail-action-status')
    expect(read('src/app/(frontend)/styles.css')).toContain('.content-detail-retry')
    expect(publisher).toContain('function startNewContent()')
    expect(publisher).toContain("setDraft(null)")
    expect(publisher).toContain('新建内容')

    expect(publisher).toContain('const controller = new AbortController()')
    expect(publisher).toContain('signal: controller.signal')
    expect(publisher).toContain("caught instanceof DOMException && caught.name === 'AbortError'")
    expect(publisher).toContain('controller.abort()')

    expect(publisher).toContain('disabled={busy || reviewLocked}')
    expect(publisher).toContain('<div className="lr-composer-card" aria-busy={busy}>')

    expect(publisher).toContain('当前状态')
    expect(publisher).toContain('版本 {draft.version}')

    expect(publisher).toContain('const [preview, setPreview]')
    expect(publisher).toContain('aria-label="发布预览"')
    expect(publisher).toContain("const CONTENT_MUTATED_EVENT = 'luckread:content-mutated'")
    expect(publisher).toContain('window.dispatchEvent(new Event(CONTENT_MUTATED_EVENT))')
    expect(publisher).toContain("type === 'video' && !assets.some(isVideoAsset)")
    expect(publisher).toContain('className="lr-asset-preview"')
    expect(publisher).toContain('asset.mimeType.startsWith(\'video/\')')


    expect(updateRoute).toContain('export async function GET')
    expect(updateRoute).toContain("method: 'GET'")
    expect(publisher).toContain("credentials: 'include'")
    expect(contentClient).toContain('resolveCookieContentPrincipal')
    expect(createRoute).toContain('resolveCookieContentPrincipal')
    expect(read('src/app/api/v1/contents/route.ts')).toContain('resolveCookieContentPrincipal')
    expect(read('src/app/api/v1/contents/route.ts')).toContain("pathname: '/internal/content/contents'")
    expect(read('src/app/api/v1/contents/route.ts')).toContain('validateContentListQuery')
    expect(createRoute).toContain("pathname: '/internal/content/contents'")
    expect(updateRoute).toContain('export async function DELETE')
    expect(updateRoute).toContain('export async function PATCH')
    expect(updateRoute).toContain('resolveCookieContentPrincipal')
    expect(updateRoute).toContain("method: 'PATCH'")
    expect(updateRoute).toContain('/internal/content/contents/')
    expect(stateRoute).toContain('resolveCookieContentPrincipal')
    expect(stateRoute).toContain('/internal/content/contents/')
    expect(publisher).toContain('发布前自检')
    expect(publisher).toContain('AI 使用方式（请据实选择）')
    expect(publisher).toContain('整篇 AI 生成（禁止直接发布）')
    expect(publisher).toContain('humanContribution')
    expect(preflightRoute).toContain('resolveCookieContentPrincipal')
    expect(preflightRoute).toContain('/internal/content/contents/')
    expect(preflightRoute).toContain('/preflight')
    expect(preflightRoute).toContain('/preflight')
  })

  it('exposes the creator-owned content management read slice', () => {
    const view = read('src/app/(frontend)/creator-center/CreatorStudio.tsx')
    const list = read('src/app/(payload)/v1beta/CreatorContentList.tsx')
    const route = read('src/app/(payload)/api/creator/contents/route.ts')
    const client = read('src/content/w03-content-client.ts')

    expect(view).toContain("import CreatorContentList from '../../(payload)/v1beta/CreatorContentList'")
    expect(view).toContain('<CreatorContentList loginPath={adminMode ? \'/admin/login\' : \'/login\'} />')

    expect(list).toContain("/api/creator/contents?")
    expect(list).toContain("['DRAFT', 'REJECTED'].includes(item.state)")
    expect(list).toContain("item.state === 'PUBLISHED'")
    expect(list).toContain("async function transition(item: Item, to: 'PUBLISHED' | 'UNPUBLISHED' | 'ARCHIVED' | 'RESTORED' | 'DRAFT')")
    expect(list).toContain("/api/creator/contents/")
    expect(list).toContain("/state")
    expect(list).toContain("method: 'POST'")
    expect(list).toContain("Idempotency-Key")
    expect(list).toContain("crypto.randomUUID()")
    expect(list).toContain("['UNPUBLISHED', '已下线']")
    expect(list).toContain("['ARCHIVED', '已归档']")
    expect(list).toContain("['DELETED', '已删除']")
    expect(list).toContain("['RESTORED', '已恢复']")
    expect(list).toContain("transition(item, 'ARCHIVED')")
    expect(list).toContain("transition(item, 'RESTORED')")
    expect(list).toContain("transition(item, 'DRAFT')")
    expect(list).toContain('async function deleteContent(item: Item)')
    expect(list).toContain("method: 'DELETE'")
    expect(list).toContain("'If-Match': `W/\"${item.version}\"`")
    expect(list).toContain("'Idempotency-Key'")
    expect(list).toContain("window.confirm('确定要删除“' + item.title + '”吗？删除后内容会进入已删除状态。')")
    expect(list).toContain("['DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'ARCHIVED'].includes(item.state)")
    expect(list).toContain("onClick={() => void deleteContent(item)}")
    expect(list).toContain('删除')
    expect(list).toContain("'恢复为草稿'")
    expect(list).toContain("'归档'")
    expect(list).toContain("['REJECTED', '审核退回']")
    expect(list).toContain("['APPROVED', '待发布']")
    expect(list).toContain("['SCHEDULED', '定时发布']")
    expect(list).toContain("'下线'")
    expect(list).toContain("'重新发布'")
    expect(list).toContain('async function requestTransition(')
    expect(list).toContain('async function moveToDraftForEdit(item: Item)')
    expect(list).toContain('async function unpublishAndEdit(item: Item)')
    expect(list).toContain("requestTransition(item.id, 'DRAFT', item.version)")
    expect(list).toContain("requestTransition(item.id, 'UNPUBLISHED', item.version)")
    expect(list).toContain("requestTransition(item.id, 'DRAFT', unpublishedVersion)")
    expect(list).toContain(`/publish?draft=\${encodeURIComponent(item.id)}&version=\${draftVersion}`)
    expect(list).toContain('下线并编辑')
    expect(list).toContain('转为草稿编辑')
    expect(list).toContain("window.addEventListener('luckread:content-mutated'")
    expect(list).toContain("window.removeEventListener('luckread:content-mutated'")
    expect(list).toContain("href={\`/content/\${encodeURIComponent(item.slug || item.id)}\`}")
    expect(list).toContain("item.state === 'APPROVED'")
    expect(list).toContain("transition(item, 'PUBLISHED')")
    expect(list).toContain('立即发布')
    expect(list).toContain('加载更多')
    expect(list).toContain('page.hasMore && page.nextCursor')
    expect(list).toContain('role="status" aria-busy="true"')
    expect(list).toContain('<div className={styles.contentManageState} role="alert">')
    expect(list).toContain('aria-busy={loadingMore}')
    expect(list).toContain('<section aria-busy={loading || actionId !== null} className={styles.contentManageSection}>')
    expect(list).toContain('aria-busy={actionId === item.id}')
    expect(list).toContain('items: [...current.items, ...(next.items ?? [])]')
    expect(list).toContain('const [loadingMore, setLoadingMore]')
    expect(list).toContain('const requestIdRef = useRef(0)')
    expect(list).toContain('const requestId = ++requestIdRef.current')
    expect(list).toContain('if (requestId !== requestIdRef.current) return')
    expect(list).toContain('if (cursor) setLoadingMore(true)')
    expect(list).toContain('disabled={loadingMore}')
    expect(list).toContain("loadingMore ? '加载中…' : '加载更多'")
    expect(route).toContain('export async function GET')
    expect(route).toContain('/internal/content/creator-contents')
    expect(client).toContain('X-LuckRead-Principal-User-Id')
  })

  it('organizes the creator center around creator-first workflows', () => {
    const view = read('src/app/(frontend)/creator-center/CreatorStudio.tsx')
    const assistant = read('src/app/(payload)/v1beta/CreatorCenterAssistant.tsx')
    const styles = read('src/app/(payload)/v1beta/creator-center.module.css')
    const moderation = read('src/app/(payload)/v1beta/CreatorModerationQueue.tsx')


    expect(view).toContain('内容管理')
    expect(view).toContain('发布中心')
    expect(view).toContain('审核与发布')
    expect(view).toContain('素材库')
    expect(view).toContain('数据中心')
    expect(view).toContain('粉丝与关注')
    expect(view).toContain('收益中心')
    expect(view).toContain('快速创作')
    expect(view).toContain('写文章')
    expect(view).toContain('发动态')
    expect(view).toContain('发视频')
    expect(view).toContain('id="overview"')
    expect(view).toContain('id="content"')
    expect(view).toContain('id="publisher"')
    expect(view).toContain('id="quality"')
    expect(view).toContain('id="assets"')
    expect(view).toContain('<CreatorCenterAssistant />')
    expect(assistant).toContain('className={styles.floatingAssistant}')
    expect(assistant).toContain('aria-controls="creator-check-assistant"')
    expect(assistant).toContain("textContent?.trim() === '发布前自检'")

    expect(styles).toContain('.creatorLayout')
    expect(styles).toContain('.sidebar')
    expect(styles).toContain('.quickCreate')
    expect(styles).toContain('.toolGrid')
    expect(styles).toContain('.futureGrid')
    expect(styles).toContain('.creatorLayout a:focus-visible')
    expect(styles).toContain('.creatorLayout button:focus-visible')
    expect(moderation).toContain("fetch('/api/v1/admin/moderation/queue?limit=20'")
    expect(moderation).toContain("/api/v1/admin/moderation/cases/' + encodeURIComponent(item.caseId) + '/decision")
    expect(moderation).toContain(`'If-Match': 'W/"' + item.version + '"'`)
    expect(moderation).toContain("'Idempotency-Key': crypto.randomUUID()")
    expect(moderation).toContain("decision: outcome")
    expect(moderation).toContain("expectedVersion: item.version")
    expect(moderation).toContain("outcome === 'REJECTED' ? 'BLOCK' : 'INFO'")
    expect(view).toContain('{adminMode ? <CreatorModerationQueue /> : null}')

    expect(styles).toContain('.creatorLayout select:focus-visible')
  })

  it('stabilizes the creator media library loader around its login dependency', () => {
    const assets = read('src/app/(payload)/v1beta/CreatorAssetLibrary.tsx')
    expect(assets).toContain("import { ChangeEvent, useCallback, useEffect, useState } from 'react'")
    expect(assets).toContain('const load = useCallback(async (page = 1, append = false) => {')
    expect(assets).toContain('}, [loginPath])')
    expect(assets).toContain('}, [load])')
  })

  it('uses the stable v1 creator media library instead of a second media authority', () => {
    const view = read('src/app/(frontend)/creator-center/CreatorStudio.tsx')
    const assets = read('src/app/(payload)/v1beta/CreatorAssetLibrary.tsx')

    expect(view).toContain("import CreatorAssetLibrary from '../../(payload)/v1beta/CreatorAssetLibrary'")
    expect(view).toContain('<CreatorAssetLibrary adminMode={adminMode} loginPath={adminMode ? \'/admin/login\' : \'/login\'} />')
    expect(assets).toContain("fetch('/api/v1/media?limit=8&page=' + String(page)")
    expect(assets).toContain('pageNumber + 1')
    expect(assets).toContain('totalPages')
    expect(assets).toContain('加载更多素材')
    expect(assets).toContain("fetch('/api/v1/media', {")
    expect(assets).toContain("method: 'POST'")
    expect(assets).toContain("headers: { 'Idempotency-Key': 'media-upload:' + crypto.randomUUID() }")
    expect(assets).toContain("form.append('file', file)")
    expect(assets).toContain('accept="image/*,video/*"')
    expect(assets).toContain('上传素材')
    expect(assets).toContain("method: 'DELETE'")
    expect(assets).toContain("'/api/v1/media/' + encodeURIComponent(String(id))")
    expect(assets).toContain("credentials: 'include'")
    expect(assets).toContain("const returnTo = window.location.pathname + window.location.search + window.location.hash")
    expect(assets).toContain("window.location.assign(loginPath + '?returnTo=' + encodeURIComponent(returnTo))")
    expect(assets.match(/response\.status === 401/g)?.length).toBe(4)
    expect(assets).toContain('mimeType.startsWith(\'video/\')')
    expect(assets).not.toContain('D1Database')
    expect(assets).not.toContain('R2Bucket')
  })

  it('lets creators update media alt text through the stable media API', () => {
    const assets = read('src/app/(payload)/v1beta/CreatorAssetLibrary.tsx')

    expect(assets).toContain("method: 'PATCH'")
    expect(assets).toContain("'/api/v1/media/' + encodeURIComponent(String(item.id))")
    expect(assets).toContain("JSON.stringify({ alt })")
    expect(assets).toContain('maxLength={1000}')
    expect(assets).toContain('编辑说明')
    expect(assets).toContain('素材说明不能为空')
  })

  it('exposes login submission and error status', () => {
    const registerForm = read('src/app/(frontend)/register/RegisterForm.tsx')
    const loginForm = read('src/app/(frontend)/login/LoginForm.tsx')

    expect(registerForm).toContain('<form aria-busy={status === \'submitting\'} className="registerForm" onSubmit={handleSubmit} noValidate>')
    expect(registerForm).toContain("fetch('/api/v1/auth/register'")
    expect(registerForm).not.toContain("fetch('/auth/register'")
    expect(loginForm).toContain('<form className="lr-auth-form" onSubmit={submit} aria-busy={busy}>')
    expect(loginForm).toContain('<div className="lr-error" role="alert" aria-live="assertive">{error}</div>')
    expect(loginForm).toContain('<button aria-busy={busy} disabled={busy} type="submit">')
  })

  it('exposes the user subscription page on the stable subscription API', () => {
    const page = read('src/app/(frontend)/me/subscriptions/page.tsx')
    const home = read('src/app/(frontend)/page.tsx')
    const css = read('src/app/(frontend)/me/subscriptions/subscriptions.css')

    expect(page).toContain("'/api/v1/memberships/subscriptions?limit=20&page=' + String(page)")
    expect(page).toContain("const returnTo = window.location.pathname + window.location.search + window.location.hash")
    expect(page).toContain("window.location.assign('/login?returnTo=' + encodeURIComponent(returnTo))")
    expect(page).toContain("method: 'POST'")
    expect(page).toContain("'If-Match': item.etag")
    expect(page).toContain("item.creatorId ? '创作者订阅' : '会员订阅'")
    expect(page).not.toContain("window.prompt('请输入新的订阅方案 ID'")
    expect(page).toContain('方案变更将在正式方案目录接入后开放')
    expect(page).toContain("'/users/' + encodeURIComponent(item.creatorId)")
    expect(page).toContain('查看创作者主页')
    expect(page).toContain("method: 'POST'")
    expect(page).toContain("'Idempotency-Key': operation + ':' + item.subscriptionId + ':' + item.etag")
    expect(page).toContain("transition(item, 'cancel')")
    expect(page).toContain("transition(item, 'pause')")
    expect(page).toContain("transition(item, 'resume')")
    expect(page).toContain("if (response.status === 401)")
    expect(page).toContain("window.location.assign('/login?returnTo=' + encodeURIComponent(returnTo))")
    expect(page).toContain("pageNumber + 1")
    expect(page).toContain("append ? [...current, ...data.data!.docs!] : data.data!.docs!")
    expect(page).toContain('hasNextPage')
    expect(page).toContain('加载更多订阅')
    expect(page).toContain("statusLabel")
    expect(page).not.toContain('entitlement')
    expect(home).toContain('href="/me/subscriptions"')
    expect(css).toContain('.my-subscriptions')
    expect(css).toContain('.subscription-card')
  })

  it('keeps frontend and Admin on the same Better Auth/W02 session lifecycle', () => {
    const authClient = read('src/auth/w02-session-client.ts')
    const users = read('src/collections/Users.ts')
    expect(authClient).toContain('getBetterAuthPrincipal')
    expect(users).toContain('disableLocalStrategy: true')
    expect(users).toContain("strategies: [betterAuthPayloadStrategy]")
    expect(users).not.toContain('accessToken')
    expect(users).not.toContain('refreshToken')
  })

  it('keeps only native Payload import-map entries after moving creator UI to v1beta', () => {
    const importMap = read('src/app/(payload)/admin/importMap.js')

    expect(importMap).toContain('@payloadcms/storage-r2/client')
    expect(importMap).toMatch(/@payloadcms\/(?:ui\/rsc|next\/rsc)#CollectionCards/)
    expect(importMap).not.toContain('CreatorCenterAction')
    expect(importMap).not.toContain('/app/(payload)/admin/CreatorCenter')
    expect(importMap).not.toContain('/app/(payload)/v1beta/CreatorCenter')
  })

  it('supports a persistent Chinese/English creator studio interface toggle', () => {
    const toggle = read('src/app/(frontend)/creator-center/CreatorLanguageToggle.tsx')
    const page = read('src/app/(frontend)/creator-center/page.tsx')
    const home = read('src/app/(frontend)/page.tsx')
    const view = read('src/app/(frontend)/creator-center/CreatorStudio.tsx')
    const styles = read('src/app/(payload)/v1beta/creator-center.module.css')

    expect(toggle).toContain("'use client'")
    expect(toggle).toContain("const COOKIE_NAME = 'luckread-ui-locale'")
    expect(toggle).toContain("中文")
    expect(toggle).toContain("English")
    expect(toggle).toContain('aria-pressed')
    expect(toggle).toContain("Max-Age=31536000")
    expect(page).toContain("(await cookies()).get('luckread-ui-locale')?.value")
    expect(page).toContain("localeCookie === 'en-US' ? 'en-US' : 'zh-CN'")
    expect(page).toContain('locale={locale}')
    expect(home).toContain("import CreatorLanguageToggle from './creator-center/CreatorLanguageToggle'")
    expect(home).toContain("const localeCookie = (await cookies()).get('luckread-ui-locale')?.value")
    expect(home).toContain('<CreatorLanguageToggle locale={locale} />')
    expect(view).toContain("locale?: StudioLocale")
    expect(view).toContain('navigationByLocale')
    expect(view).toContain('<CreatorLanguageToggle locale={locale} />')
    expect(view).toContain("locale === 'en-US' ? 'Publish check' : '发布检测'")
    expect(view).toContain("locale === 'en-US' ? 'Audience' : '粉丝'")
    expect(styles).toContain('.languageSwitch')
    expect(styles).toContain('.languageSwitchButtonActive')
  })


})
