import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const read = (relativePath: string) => readFileSync(resolve(process.cwd(), relativePath), 'utf8')

describe('Creator Center admin extension', () => {
  it('registers as a separate Payload Admin root view without replacing native views', () => {
    const config = read('src/payload.config.ts')

    expect(config).toContain('creatorCenter: {')
    expect(config).toContain("Component: '/app/(payload)/admin/CreatorCenter#CreatorCenter'")
    expect(config).toContain("path: '/creator-center'")
    expect(config).toContain("actions: ['/app/(payload)/admin/CreatorCenterAction#CreatorCenterAction']")
  })

  it('uses the native Payload admin request principal instead of a second login/session system', () => {
    const view = read('src/app/(payload)/admin/CreatorCenter.tsx')

    expect(view).toContain('AdminViewServerProps')
    expect(view).toContain('initPageResult.req.user')
    expect(view).not.toContain('sessionStorage')
    expect(view).not.toContain('accessToken')
    expect(view).not.toContain('refreshToken')
  })

  it('embeds the existing publisher with a scoped W03 content bridge', () => {
    const view = read('src/app/(payload)/admin/CreatorCenter.tsx')
    const publisher = read('src/app/(frontend)/publish/PublishComposer.tsx')
    const contentDetail = read('src/app/(frontend)/content/[contentId]/page.tsx')
    const homeFeed = read('src/app/(frontend)/HomeContentFeed.tsx')
    const contentBrowse = read('src/app/(frontend)/content/page.tsx')
    const page = read('src/app/(frontend)/publish/page.tsx')
    const contentClient = read('src/content/w03-content-client.ts')
    const createRoute = read('src/app/(payload)/api/creator/contents/route.ts')
    const updateRoute = read('src/app/(payload)/api/creator/contents/[contentId]/route.ts')
    const stateRoute = read('src/app/(payload)/api/creator/contents/[contentId]/state/route.ts')
    const preflightRoute = read('src/app/(payload)/api/creator/contents/[contentId]/preflight/route.ts')

    expect(view).toContain('<PublishComposer contentBasePath="/api/creator/contents" />')
    expect(publisher).toContain("contentBasePath = '/api/v1/contents'")
    expect(publisher).toContain("credentials: 'include'")
    expect(publisher).not.toContain('sessionStorage')
    expect(publisher).not.toContain('luckread.accessToken')
    expect(publisher).not.toContain('luckread.refreshToken')
    expect(publisher).not.toContain("Authorization', 'Bearer '")
    expect(publisher).toContain('const [draft, setDraft]')
    expect(publisher).toContain('const [savedBody, setSavedBody]')
    expect(publisher).toContain('const isUpdate = Boolean(draft?.id && draft.etag)')
    expect(publisher).toContain("method: isUpdate ? 'PATCH' : 'POST'")
    expect(publisher).toContain("'If-Match': draft!.etag")
    expect(publisher).toContain('async function discardDraft()')
    expect(publisher).toContain("method: 'DELETE'")
    expect(publisher).toContain("'If-Match': draft.etag")
    expect(publisher).toContain('useEffect')
    expect(publisher).toContain("searchParams.get('draft')")
    expect(page).toContain("normalizeContentType")
    expect(page).toContain("<PublishComposer initialType={initialType} />")
    expect(publisher).toContain("method: 'GET'")
    expect(publisher).toContain('window.history.replaceState')
    expect(publisher).toContain('async function copyDraftLink()')
    expect(publisher).toContain('navigator.clipboard.writeText')
    expect(publisher).toContain("'复制恢复链接'")
    expect(publisher).toContain('const stateLabel = draft?.state')
    expect(publisher).toContain("const reviewLocked = draft?.state === 'PENDING_REVIEW'")
    expect(publisher).toContain("const returnTo = window.location.pathname + window.location.search + window.location.hash")
    expect(publisher).toContain("router.replace('/login?returnTo=' + encodeURIComponent(returnTo))")
    expect(contentDetail).toContain("const [actionMessage, setActionMessage] = useState('')")
    expect(homeFeed).toContain('const cover = item.coverRef')
    expect(homeFeed).toContain("alt={item.title ? item.title + '封面' : '内容封面'}")
    expect(homeFeed).not.toContain('item.coverRef || item.mediaRefs?.[0]')
    expect(homeFeed).toContain('content-feed-card-skeleton')
    expect(homeFeed).toContain('const [retryKey, setRetryKey] = useState(0)')
    expect(homeFeed).toContain('setRetryKey((value) => value + 1)')
    expect(homeFeed).toContain('Array.from({ length: 3 }')
    expect(homeFeed).toContain("const [error, setError] = useState(false)")
    expect(homeFeed).toContain('内容暂时无法加载。')
    expect(contentBrowse).toContain('content-feed-card-skeleton')
    expect(contentBrowse).toContain('Array.from({ length: 6 }')
    expect(contentBrowse).toContain('aria-busy="true"')
    expect(contentBrowse).toContain('aria-busy={loadingMore}')
    expect(contentBrowse).toContain('const requestIdRef = useRef(0)')
    expect(contentBrowse).toContain('const requestId = ++requestIdRef.current')
    expect(contentBrowse).toContain('if (requestId !== requestIdRef.current) return')
    expect(contentBrowse).toContain('role="status"')
    expect(read('src/app/(frontend)/styles.css')).toContain('@media (prefers-reduced-motion: reduce)')
    expect(read('src/app/(frontend)/styles.css')).toContain('.content-feed-card-skeleton')
    expect(contentDetail).toContain("setActionMessage('无法复制链接，请从地址栏复制当前页面地址。')")
    expect(contentDetail).toContain('content-detail-action-status')
    expect(contentDetail).toContain('const [retryKey, setRetryKey] = useState(0)')
    expect(contentDetail).toContain('setRetryKey((value) => value + 1)')
    expect(contentDetail).toContain('content-detail-retry')
    expect(contentDetail).toContain('<main aria-busy={loading} className="content-detail">')
    expect(contentDetail).toContain('<p className="content-detail-state" role="status">正在加载内容…</p>')
    expect(contentDetail).toContain("aria-label={content.title + ' 视频 ' + (index + 1)}")
    expect(contentDetail).toContain('const controller = new AbortController()')
    expect(contentDetail).toContain('signal: controller.signal')
    expect(contentDetail).toContain("cause.name === 'AbortError'")
    expect(contentDetail).toContain('controller.abort()')
    expect(contentDetail).toContain("alt={content.title + ' 封面'}")
    expect(contentDetail).toContain("alt={content.title + ' 配图 ' + (index + 1)}")
    expect(read('src/app/(frontend)/styles.css')).toContain('.content-detail-action-status')
    expect(read('src/app/(frontend)/styles.css')).toContain('.content-detail-retry')
    expect(publisher).toContain('function startNewContent()')
    expect(publisher).toContain("setDraft(null)")
    expect(publisher).toContain('新建内容')

    expect(publisher).toContain('disabled={busy || reviewLocked}')
    expect(publisher).toContain('<div className="lr-composer-card" aria-busy={busy}>')

    expect(publisher).toContain('当前状态')
    expect(publisher).toContain('版本 {draft.version}')

    expect(publisher).toContain('const [preview, setPreview]')
    expect(publisher).toContain('aria-label="发布预览"')
    expect(publisher).toContain("const CONTENT_MUTATED_EVENT = 'luckread:content-mutated'")
    expect(publisher).toContain('window.dispatchEvent(new Event(CONTENT_MUTATED_EVENT))')
    expect(publisher).toContain("type === 'video' && assets.length === 0")
    expect(publisher).toContain('className="lr-asset-preview"')
    expect(publisher).toContain('asset.mimeType.startsWith(\'video/\')')


    expect(updateRoute).toContain('export async function GET')
    expect(updateRoute).toContain("method: 'GET'")
    expect(publisher).toContain("credentials: 'include'")
    expect(contentClient).toContain('resolveCookieContentPrincipal')
    expect(createRoute).toContain('resolveCookieContentPrincipal')
    expect(read('src/app/api/v1/contents/route.ts')).toContain('resolveCookieContentPrincipal')
    expect(read('src/app/api/v1/contents/route.ts')).toContain("pathname: '/internal/content/contents'")
    expect(createRoute).toContain("pathname: '/internal/content/contents'")
    expect(updateRoute).toContain('export async function DELETE')
    expect(updateRoute).toContain('export async function PATCH')
    expect(updateRoute).toContain('resolveCookieContentPrincipal')
    expect(updateRoute).toContain("method: 'PATCH'")
    expect(updateRoute).toContain('/internal/content/contents/')
    expect(stateRoute).toContain('resolveCookieContentPrincipal')
    expect(stateRoute).toContain('/internal/content/contents/')
    expect(publisher).toContain('发布前自检')
    expect(publisher).toContain('AI 使用方式（请据实选择）')
    expect(publisher).toContain('整篇 AI 生成（禁止直接发布）')
    expect(publisher).toContain('humanContribution')
    expect(preflightRoute).toContain('resolveCookieContentPrincipal')
    expect(preflightRoute).toContain('/internal/content/contents/')
    expect(preflightRoute).toContain('/preflight')
    expect(preflightRoute).toContain('/preflight')
  })

  it('exposes the creator-owned content management read slice', () => {
    const view = read('src/app/(payload)/admin/CreatorCenter.tsx')
    const list = read('src/app/(payload)/admin/CreatorContentList.tsx')
    const route = read('src/app/(payload)/api/creator/contents/route.ts')
    const client = read('src/content/w03-content-client.ts')

    expect(view).toContain("import CreatorContentList from './CreatorContentList'")
    expect(view).toContain('<CreatorContentList />')
    expect(list).toContain("/api/creator/contents?")
    expect(list).toContain("['DRAFT', 'REJECTED'].includes(item.state)")
    expect(list).toContain("item.state === 'PUBLISHED'")
    expect(list).toContain("async function transition(item: Item, to: 'PUBLISHED' | 'UNPUBLISHED' | 'ARCHIVED' | 'RESTORED' | 'DRAFT')")
    expect(list).toContain("/api/creator/contents/")
    expect(list).toContain("/state")
    expect(list).toContain("method: 'POST'")
    expect(list).toContain("Idempotency-Key")
    expect(list).toContain("crypto.randomUUID()")
    expect(list).toContain("['UNPUBLISHED', '已下线']")
    expect(list).toContain("['ARCHIVED', '已归档']")
    expect(list).toContain("['DELETED', '已删除']")
    expect(list).toContain("['RESTORED', '已恢复']")
    expect(list).toContain("transition(item, 'ARCHIVED')")
    expect(list).toContain("transition(item, 'RESTORED')")
    expect(list).toContain("transition(item, 'DRAFT')")
    expect(list).toContain('async function deleteContent(item: Item)')
    expect(list).toContain("method: 'DELETE'")
    expect(list).toContain("'If-Match': `W/\"${item.version}\"`")
    expect(list).toContain("'Idempotency-Key'")
    expect(list).toContain("window.confirm('确定要删除“' + item.title + '”吗？删除后内容会进入已删除状态。')")
    expect(list).toContain("['DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'ARCHIVED'].includes(item.state)")
    expect(list).toContain("onClick={() => void deleteContent(item)}")
    expect(list).toContain('删除')
    expect(list).toContain("'恢复为草稿'")
    expect(list).toContain("'归档'")
    expect(list).toContain("['REJECTED', '审核退回']")
    expect(list).toContain("['APPROVED', '待发布']")
    expect(list).toContain("['SCHEDULED', '定时发布']")
    expect(list).toContain("'下线'")
    expect(list).toContain("'重新发布'")
    expect(list).toContain("window.addEventListener('luckread:content-mutated'")
    expect(list).toContain("window.removeEventListener('luckread:content-mutated'")
    expect(list).toContain("href={\`/content/\${encodeURIComponent(item.id)}\`}")
    expect(list).toContain("item.state === 'APPROVED'")
    expect(list).toContain("transition(item, 'PUBLISHED')")
    expect(list).toContain('立即发布')
    expect(list).toContain('加载更多')
    expect(list).toContain('page.hasMore && page.nextCursor')
    expect(list).toContain('role="status" aria-busy="true"')
    expect(list).toContain('<div className={styles.contentManageState} role="alert">')
    expect(list).toContain('aria-busy={loadingMore}')
    expect(list).toContain('<section aria-busy={loading || actionId !== null} className={styles.contentManageSection}>')
    expect(list).toContain('aria-busy={actionId === item.id}')
    expect(list).toContain('items: [...current.items, ...(next.items ?? [])]')
    expect(list).toContain('const [loadingMore, setLoadingMore]')
    expect(list).toContain('const requestIdRef = useRef(0)')
    expect(list).toContain('const requestId = ++requestIdRef.current')
    expect(list).toContain('if (requestId !== requestIdRef.current) return')
    expect(list).toContain('if (cursor) setLoadingMore(true)')
    expect(list).toContain('disabled={loadingMore}')
    expect(list).toContain("loadingMore ? '加载中…' : '加载更多'")
    expect(route).toContain('export async function GET')
    expect(route).toContain('/internal/content/creator-contents')
    expect(client).toContain('X-LuckRead-Principal-User-Id')
  })

  it('organizes the creator center around creator-first workflows', () => {
    const view = read('src/app/(payload)/admin/CreatorCenter.tsx')
    const assistant = read('src/app/(payload)/admin/CreatorCenterAssistant.tsx')
    const styles = read('src/app/(payload)/admin/creator-center.module.css')
    const moderation = read('src/app/(payload)/admin/CreatorModerationQueue.tsx')


    expect(view).toContain('文章管理')
    expect(view).toContain('发布中心')
    expect(view).toContain('发布检测')
    expect(view).toContain('素材库')
    expect(view).toContain('数据中心')
    expect(view).toContain('粉丝与订阅')
    expect(view).toContain('收益与权益')
    expect(view).toContain('快速创作')
    expect(view).toContain('写文章')
    expect(view).toContain('发动态')
    expect(view).toContain('发视频')
    expect(view).toContain('id="overview"')
    expect(view).toContain('id="content"')
    expect(view).toContain('id="publisher"')
    expect(view).toContain('id="quality"')
    expect(view).toContain('id="assets"')
    expect(view).toContain('<CreatorCenterAssistant />')
    expect(assistant).toContain('className={styles.floatingAssistant}')
    expect(assistant).toContain('aria-controls="creator-check-assistant"')
    expect(assistant).toContain("textContent?.trim() === '发布前自检'")

    expect(styles).toContain('.creatorLayout')
    expect(styles).toContain('.sidebar')
    expect(styles).toContain('.quickCreate')
    expect(styles).toContain('.toolGrid')
    expect(styles).toContain('.futureGrid')
    expect(styles).toContain('.creatorLayout a:focus-visible')
    expect(styles).toContain('.creatorLayout button:focus-visible')
    expect(moderation).toContain("fetch('/api/v1/admin/moderation/queue?limit=20'")
    expect(moderation).toContain("/api/v1/admin/moderation/cases/' + encodeURIComponent(item.caseId) + '/decision")
    expect(moderation).toContain("'If-Match': 'W/"' + item.version + '"'")
    expect(moderation).toContain("'Idempotency-Key': crypto.randomUUID()")
    expect(moderation).toContain("decision: outcome")
    expect(moderation).toContain("expectedVersion: item.version")
    expect(moderation).toContain("outcome === 'REJECTED' ? 'BLOCK' : 'INFO'")
    expect(view).toContain('<CreatorModerationQueue />')

    expect(styles).toContain('.creatorLayout select:focus-visible')
  })

  it('uses the stable v1 creator media library instead of a second media authority', () => {
    const view = read('src/app/(payload)/admin/CreatorCenter.tsx')
    const assets = read('src/app/(payload)/admin/CreatorAssetLibrary.tsx')

    expect(view).toContain("import CreatorAssetLibrary from './CreatorAssetLibrary'")
    expect(view).toContain('<CreatorAssetLibrary />')
    expect(assets).toContain("fetch('/api/v1/media?limit=8&page=1'")
    expect(assets).toContain("method: 'DELETE'")
    expect(assets).toContain("'/api/v1/media/' + encodeURIComponent(String(id))")
    expect(assets).toContain("credentials: 'include'")
    expect(assets).toContain('mimeType.startsWith(\'video/\')')
    expect(assets).not.toContain('D1Database')
    expect(assets).not.toContain('R2Bucket')
  })

  it('lets creators update media alt text through the stable media API', () => {
    const assets = read('src/app/(payload)/admin/CreatorAssetLibrary.tsx')

    expect(assets).toContain("method: 'PATCH'")
    expect(assets).toContain("'/api/v1/media/' + encodeURIComponent(String(item.id))")
    expect(assets).toContain("JSON.stringify({ alt })")
    expect(assets).toContain('maxLength={1000}')
    expect(assets).toContain('编辑说明')
    expect(assets).toContain('素材说明不能为空')
  })

  it('exposes login submission and error status', () => {
    const registerForm = read('src/app/(frontend)/register/RegisterForm.tsx')
    const loginForm = read('src/app/(frontend)/login/LoginForm.tsx')

    expect(registerForm).toContain('<form aria-busy={status === \'submitting\'} className="registerForm" onSubmit={handleSubmit} noValidate>')
    expect(loginForm).toContain('<form className="lr-auth-form" onSubmit={submit} aria-busy={busy}>')
    expect(loginForm).toContain('<div className="lr-error" role="alert" aria-live="assertive">{error}</div>')
    expect(loginForm).toContain('<button aria-busy={busy} disabled={busy} type="submit">')
  })

  it('exposes the user subscription page on the stable subscription API', () => {
    const page = read('src/app/(frontend)/me/subscriptions/page.tsx')
    const home = read('src/app/(frontend)/page.tsx')
    const css = read('src/app/(frontend)/me/subscriptions/subscriptions.css')

    expect(page).toContain("fetch('/api/v1/memberships/subscriptions?limit=20&page=1'")
    expect(page).toContain("method: 'POST'")
    expect(page).toContain("'If-Match': item.etag")
    expect(page).toContain("transition(item, 'cancel')")
    expect(page).toContain("transition(item, 'pause')")
    expect(page).toContain("transition(item, 'resume')")
    expect(page).toContain("statusLabel")
    expect(page).not.toContain('entitlement')
    expect(home).toContain('href="/me/subscriptions"')
    expect(css).toContain('.my-subscriptions')
    expect(css).toContain('.subscription-card')
  })

  it('keeps frontend and Admin on the same Payload cookie session lifecycle', () => {
    const login = read('src/app/auth/login/route.ts')
    const refresh = read('src/app/auth/refresh/route.ts')
    const logout = read('src/app/auth/logout/route.ts')
    const accessToken = read('src/auth/payload-access-token.ts')
    const sessions = read('src/app/auth/sessions/[[...segments]]/route.ts')
    const usersMe = read('src/app/(payload)/api/users/me/route.ts')
    const accountState = read('src/app/users/[userId]/account-state/route.ts')
    const loginForm = read('src/app/(frontend)/login/LoginForm.tsx')

    expect(login).toContain('buildPayloadAccessCookie')
    expect(login).toContain("'set-cookie': buildPayloadAccessCookie(access.token, access.expiresIn, request)")
    expect(refresh).toContain('buildPayloadAccessCookie')
    expect(refresh).toContain("'set-cookie': buildPayloadAccessCookie(access.token, access.expiresIn, request)")
    expect(logout).toContain('buildPayloadClearCookie(request)')
    expect(accessToken).toContain("return getCookieValue(request, 'payload-token')")
    expect(accessToken).toContain('export function getPayloadAuthorizationHeader')
    expect(sessions).toContain('getPayloadAuthorizationHeader(request)')
    expect(usersMe).toContain('readVerifiedPayloadTokenVersion(request)')
    expect(accountState).toContain('getPayloadAuthorizationHeader(request)')
    expect(loginForm).not.toContain("sessionStorage.setItem('luckread.accessToken'")
    expect(loginForm).not.toContain("sessionStorage.setItem('luckread.refreshToken'")
    expect(loginForm).not.toContain("sessionStorage.setItem('luckread.layer'")
  })

  it('keeps the existing native admin import map entries', () => {
    const importMap = read('src/app/(payload)/admin/importMap.js')

    expect(importMap).toContain('@payloadcms/storage-r2/client')
    expect(importMap).toContain('/app/(payload)/admin/CreatorCenter#CreatorCenter')
    expect(importMap).toContain('/app/(payload)/admin/CreatorCenterAction#CreatorCenterAction')
  })
})
